### ISSUE TITLE
Cloud sync doesn't work with some games

### ISSUE THREAD

**Issue by Postnozet** [pythonlover02/Proton-Sarek#14] opened 2024-12-01 17:26 UTC
Proton-GE and Proton Experimental do not have this problem.
Tested on Fate/stay night REMASTERED

**Comment by pythonlover02** [comment] 2024-12-01 21:41
> Proton-GE and Proton Experimental do not have this problem. Tested on Fate/stay night REMASTERED

Yeah its a know issue that i had been delaying to fix/work on it as i was working on this [PR](https://github.com/pythonlover02/Proton-Sarek/pull/11) and on [DXVK-Sarek](https://github.com/pythonlover02/DXVK-Sarek). Also because the issue had been only be present on Arc System Works games.

Anyway i will start looking into the issue and leave this open

**Comment by pythonlover02** [comment] 2024-12-06 15:27
> Proton-GE and Proton Experimental do not have this problem. Tested on Fate/stay night REMASTERED

I checked the code thoroughly, and the only thing that comes to mind is that the game reads the name of the compatibility tool name, which is usually "Proton" or "GE-Proton". This time, however, it receives just "Sarek" withouth the "Proton".

To see if this fixes the issue, please follow these steps:

1. Navigate to the compatibility tools directory:
   - For native Steam: `~/.steam/root/compatibilitytools.d`
   - For Flatpak Steam: `~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d/`

2. Enter the folder for the Sarek build.

3. Open the `proton` file and search for `CURRENT_PREFIX_VERSION`. Change its value from something like `Sarek[version]` to `Proton-Sarek[version]`, then save the file.

4. In the same folder, open `compatibilitytool.vdf` and change both mentions of the name (the internal name and the displayed name) to include "Proton". Save the changes.

5. Test the game to see if the issue is resolved.

**Comment by Postnozet** [comment] 2024-12-07 17:08
> > Proton-GE and Proton Experimental do not have this problem. Tested on Fate/stay night REMASTERED
> 
> I checked the code thoroughly, and the only thing that comes to mind is that the game reads the name of the compatibility tool name, which is usually "Proton" or "GE-Proton". This time, however, it receives just "Sarek" withouth the "Proton".
> 
> To see if this fixes the issue, please follow these steps:
> 
> 1. Navigate to the compatibility tools directory:
>    
>    * For native Steam: `~/.steam/root/compatibilitytools.d`
>    * For Flatpak Steam: `~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d/`
> 2. Enter the folder for the Sarek build.
> 3. Open the `proton` file and search for `CURRENT_PREFIX_VERSION`. Change its value from something like `Sarek[version]` to `Proton-Sarek[version]`, then save the file.
> 4. In the same folder, open `compatibilitytool.vdf` and change both mentions of the name (the internal name and the displayed name) to include "Proton". Save the changes.
> 5. Test the game to see if the issue is resolved.

Unfortunately this doesn't help

**Comment by Postnozet** [comment] 2024-12-07 22:26
Ignore my previous post. It actually worked.

**Comment by pythonlover02** [comment] 2024-12-12 14:22
> Ignore my previous post. It actually worked.

It will be fixed in the new release, it will take some time as i am not at home at the moment.

**Comment by pythonlover02** [comment] 2024-12-13 22:59
Its fixed on this new [release](https://github.com/pythonlover02/Proton-Sarek/releases/tag/Proton-Sarek9-21) *:)*

**Closed by pythonlover02** 2024-12-13 22:59 UTC
